# -- coding: utf-8 --

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages
import os

APP = ['keypad.py']
APP_NAME = "Keypad"
VERSION = "0.0.1"

DATA_FILES = [(d, [os.path.join(d,f) for f in files])
    for d, folders, files in os.walk('./share')]
OPTIONS = {
    'iconfile': './share/Keypad.icns',
    'plist': {
        'LSUIElement': True,
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Keypad emulator",
        'CFBundleIdentifier': "red-box-labs.keypad",
        'CFBundleVersion': VERSION,
        'CFBundleShortVersionString': VERSION,
        'NSHumanReadableCopyright': u"Copyright © 2018, Jon Elmer, All Rights Reserved"
    },
}

setup(
    name=APP_NAME,
    version=VERSION,
    app=APP,
    data_files=DATA_FILES,
    packages=find_packages(),
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
