"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup, find_packages
import os

APP = ['keypad.py']
DATA_FILES = [(d, [os.path.join(d,f) for f in files])
    for d, folders, files in os.walk('./share')]
DATA_FILES.append('Keypad.icns')
OPTIONS = {
    'iconfile': './Keypad.icns',
    'plist': {
        'LSUIElement': True,
        'packages': ['rumps', 'objc']
    },
    }

setup(
    name="keypad",
    version="0.2",
    app=APP,
    data_files=DATA_FILES,
    packages=find_packages(),
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
